server:
  port: 8761

spring:
  application:
    name: eureka1

eureka:
  instance:
    hostname: eureka1
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka1:8761/eureka/